### ISSUE TITLE
s390x: array index out of range

### ISSUE THREAD

**Issue by reinerh** [google/enjarify#35]
When running enjarify on s390x it fails with the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/enjarify/main.py", line 107, in <module>
    main()
  File "/usr/lib/python3/dist-packages/enjarify/main.py", line 97, in main
    translate(data, opts=opts, classes=classes, errors=errors)
  File "/usr/lib/python3/dist-packages/enjarify/main.py", line 27, in translate
    dex = parsedex.DexFile(data)
  File "/usr/lib/python3/dist-packages/enjarify/parsedex.py", line 258, in __init__
    self.classes.append(DexClass(self, defs.off, i))
  File "/usr/lib/python3/dist-packages/enjarify/parsedex.py", line 205, in __init__
    self.name = dex.clsType(words[0])
  File "/usr/lib/python3/dist-packages/enjarify/parsedex.py", line 274, in clsType
    desc = self.type(i)
  File "/usr/lib/python3/dist-packages/enjarify/parsedex.py", line 270, in type
    return self.string(self.u32s[self.type_ids.off//4 + i])
IndexError: array index out of range
```

The dex file used is available here: https://anonscm.debian.org/git/reproducible/diffoscope.git/tree/tests/data/test1.dex

**Comment by Storyyeller** [comment]
1. Are you sure the dex file is valid?
2. What endianess are you running under?

**Comment by reinerh** [comment]
Yes, the dex file is valid. It can be decoded correctly on several other architectures.
s390x is big endian.

**Comment by Storyyeller** [comment]
That would explain it. The Python version uses arrays in an attempt to make things faster, but that relies on the platform being little endian. I thought about adding a fallback in the case of big endianness, but I didn't think anybody actually used big endian in the real world. Sorry about that.

Perhaps the easiest approach would be to just remove the array stuff. I'm not sure whether it actually makes a meaningful difference to performance.

**Comment by Storyyeller** [comment]
I went ahead and removed use of arrays. This leads to a noticeable decrease in performance, but in the long term, I expect most people to use Rust anyway.
