### ISSUE TITLE
Unknown problem

### ISSUE THREAD

**Issue by plutec** [google/enjarify#8]
Hi, I obtain the same error several times with different samples:

Using python3 as Python interperter
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/asanchez/Installations/enjarify_project/enjarify/main.py", line 102, in <module>
    main()
  File "/home/asanchez/Installations/enjarify_project/enjarify/main.py", line 92, in main
    translate(data, opts=opts, classes=classes, errors=errors)
  File "/home/asanchez/Installations/enjarify_project/enjarify/main.py", line 27, in translate
    dex = parsedex.DexFile(data)
  File "/home/asanchez/Installations/enjarify_project/enjarify/parsedex.py", line 234, in __init__
    self.u16s = array.array('H', data)
ValueError: string length not a multiple of item size

The last time was with this sample:
https://koodous.com/apks/6a4ec95ce3f6a88786e8beb9ed68e8d7920cd9eedf202b3dcaca01a8e67da459

Thanks for you project!

**Comment by Storyyeller** [comment]
I can't reproduce this.

For com.zrgiu.antivirus.apk (sha256 6a4ec95ce3f6a88786e8beb9ed68e8d7920cd9eedf202b3dcaca01a8e67da459), I get no errors with both pypy and cpython.
